### ISSUE TITLE
v3.29.0.14版本测速和真延迟都失效了，测试之前版本是正常的。

### ISSUE THREAD

**Issue by ThreeSourLemon** [crazypeace/v2rayN-3.29-VLESS#12]
v3.29.0.14版本测速和真延迟都失效了，测试之前版本是正常的。

**Comment by crazypeace** [comment]
感谢反馈!
抱歉给你带来不便.

请重新下载 core.zip (我已更新)
https://github.com/crazypeace/v2rayN-3.29-VLESS/releases/download/v3.29.0.14/v2rayN-VLESS-Core-v3.29.0.14.zip

如果你是使用 v2rayn.zip 并自己添加内核的话, 请不要放入 v2ray内核.zip 中的 config.json 文件
![image](https://github.com/user-attachments/assets/568bc88c-4fc8-4d23-92d0-2a72ddc6ea5d)

**Comment by ThreeSourLemon** [comment]
> 感谢反馈! 抱歉给你带来不便.
> 
> 请在 v2rayn 目录中删除 config.josn 文件
> 
> 也可以重新下载 core.zip (我已更新) https://github.com/crazypeace/v2rayN-3.29-VLESS/releases/download/v3.29.0.14/v2rayN-VLESS-Core-v3.29.0.14.zip
> 
> 如果你是使用 v2rayn.zip 并自己添加内核的话, 请不要放入 v2ray内核.zip 中的 config.json 文件 ![image](https://private-user-images.githubusercontent.com/665889/399170073-568bc88c-4fc8-4d23-92d0-2a72ddc6ea5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU0ODU5ODgsIm5iZiI6MTczNTQ4NTY4OCwicGF0aCI6Ii82NjU4ODkvMzk5MTcwMDczLTU2OGJjODhjLTRmYzgtNGQyMy05MmQwLTJhNzJkZGM2ZWE1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyOVQxNTIxMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYTQ5OWU3YmUzMTE0YmQyNzZjYWEzNmYxMTgxMmY0Yzc4NjJmMmI1ZTlkMzY4ZWYwYzZjOWZjZTllZDgzNTk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Z3Dk1vmmgYHLiYlVi2fLHy1j7EYrvQn3PJjzI9y5sC8)

已经正常了
