### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by cdddbc** [crazypeace/v2rayN-3.29-VLESS#6]
你好，能否尝试修改一下Qv2ray未选中节点时的真延迟设置呢？每次都要选中节点开启代理才能测试真延迟，哈哈！

**Comment by crazypeace** [comment]
这个行为和 shadowrocket 要先开启代理再测试真延迟很相像. 我猜可能是一样的原因.
所以我觉得也许这是一个"特性"而不是"缺陷".

**Comment by Yzcloud** [comment]
小火箭可以批量，它不行，批量测的延迟都不是真实延迟😂
