### ISSUE TITLE
统计功能无法使用

### ISSUE THREAD

**Issue by LCW0NJUPT** [crazypeace/v2rayN-3.29-VLESS#7]
## 版本号 
v3.29.0.7

## 故障描述
- 设置中启用统计后，主页今日下载、今日上传、总下载、总上传始终为空白，重启APP无效。  
- 在3.29.0.3版本中未出现此问题。  
![image](https://github.com/crazypeace/v2rayN-3.29-VLESS/assets/27960628/f491794c-1fc5-484d-9f80-a1fc9d18793a)

## 使用协议
xray-vless-reality-vision

**Comment by crazypeace** [comment]
感谢反馈！

https://github.com/crazypeace/v2rayN-3.29-VLESS/releases/tag/v3.29.08

![image](https://github.com/crazypeace/v2rayN-3.29-VLESS/assets/665889/29a5a421-28cc-4bd2-ade0-70048d6dcfd2)

**Comment by LCW0NJUPT** [comment]
非常感谢，给您点赞👍

**Comment by LCW0NJUPT** [comment]
问题终结
