### ISSUE TITLE
希望添加vless grpc协议

### ISSUE THREAD

**Issue by x2287711259** [crazypeace/v2rayN-3.29-VLESS#8]
希望添加vless grpc协议

**Comment by crazypeace** [comment]
有什么特别的优势吗？
相对于 vless + wss,  以及 vless + reality.

**Comment by x2287711259** [comment]
延迟比较低，也能套cdn，我搭建的这个协议，下载完发现不支持
大佬能不能根据5.39修改一下，支持分片，支持reality，我发现从上6版本之后客户端就开始不好用了，3版本有点太老了

**Comment by x2287711259** [comment]
我是因为分片功能升级的最新版本，实在用不惯，比5版本要卡一些，操作逻辑也不符合习惯，原来一直用的5.39

**Comment by crazypeace** [comment]
我自己用不到, 而且我觉得对比 ws 过cdn, 也没有特别大的好处吧.
